# Generated by Django 5.2.2 on 2025-06-20 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar - $'), ('CAD', 'Canadian Dollar - $'), ('EUR', 'Euro - €'), ('GBP', 'British Pound - £'), ('JPY', 'Japanese Yen - ¥'), ('NZD', 'New Zealand Dollar - $'), ('USD', 'United States Dollar - $'), ('OTH', 'Other Currency - $')], default='AUD', max_length=3),
        ),
    ]
