# Generated by Django 5.2.2 on 2025-06-23 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_expense_options_expense_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ledgers_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
