# Generated by Django 5.2.2 on 2025-06-25 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invites_sent',
            field=models.ManyToManyField(blank=True, related_name='invites_rec', to=settings.AUTH_USER_MODEL),
        ),
    ]
