# Generated by Django 5.2.2 on 2025-07-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-updated_at']},
        ),
    ]
